# Generated by Django 5.1.6 on 2025-02-15 14:59

import Employee.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الموظف')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug الموظف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='رقم الهوية / جواز السفر')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى'), ('O', 'آخر')], max_length=1, verbose_name='الجنس')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التوظيف')),
                ('job_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='المسمى الوظيفي')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name='القسم')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب الشهري')),
                ('leave_balance', models.IntegerField(default=30, verbose_name='رصيد الإجازات')),
                ('is_active', models.BooleanField(default=True, verbose_name='هل الموظف نشط؟')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'أعزب'), ('married', 'متزوج'), ('divorced', 'مطلق'), ('widowed', 'أرمل')], max_length=10, null=True, verbose_name='الحالة الاجتماعية')),
                ('address', models.TextField(blank=True, null=True, verbose_name='عنوان السكن')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم جهة الاتصال للطوارئ')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الطوارئ')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='الجنسية')),
                ('work_permit_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم تصريح العمل')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الحساب البنكي')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=Employee.models.employee_image_upload, verbose_name='الصورة الشخصية')),
                ('passport_image', models.ImageField(blank=True, null=True, upload_to=Employee.models.passport_image_upload, verbose_name='صورة جواز السفر')),
                ('national_id_image', models.ImageField(blank=True, null=True, upload_to=Employee.models.national_id_image_upload, verbose_name='صورة الهوية الوطنية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'الموظف',
                'verbose_name_plural': 'الموظفون',
                'ordering': ['name'],
            },
        ),
    ]
