# Generated by Django 5.1.5 on 2025-02-03 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الموظف')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف')),
                ('start_date', models.DateField(verbose_name='تاريخ بدء العمل')),
                ('vacation_balance', models.PositiveIntegerField(default=21, verbose_name='رصيد الإجازات (بالأيام)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Employee/', verbose_name='صورة الموظف ')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeResidency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name='تاريخ إصدار الإقامة')),
                ('expiry_date', models.DateField(verbose_name='تاريخ انتهاء الإقامة')),
                ('residency_file', models.FileField(blank=True, null=True, upload_to='residencies/', verbose_name='ملف الإقامة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residencies', to='Employee.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'إقامة الموظف',
                'verbose_name_plural': 'إقامات الموظفين',
            },
        ),
    ]
