# Generated by Django 5.1.6 on 2025-02-26 11:20

import Employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=Employee.models.get_today_date, verbose_name='تاريخ التوظيف'),
        ),
    ]
