# Generated by Django 5.1.6 on 2025-02-27 10:45

import Employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='Residence_image',
            field=models.ImageField(blank=True, null=True, upload_to=Employee.models.residence_image_upload, verbose_name='صورة جواز السفر'),
        ),
    ]
