# Generated by Django 5.1.6 on 2025-02-27 10:48

import Employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_residence_residence_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='start_date',
            field=models.DateField(default=Employee.models.get_today_date, verbose_name='تاريخ بدء الإقامة'),
        ),
    ]
